### PR TITLE
Integration of egsorter emulator into the CMSSW Layer 1 producer

### PR DESCRIPTION
**Pull request by VourMa**
#### PR description:

This PR includes the egsorter emulator into CMSSW and modifies the egalgo and Layer 1 producer to run it.

There is the option of simplifying the egsorter emulator a bit, so we may want to discuss that.

### CODE REVIEW

**Comment by gpetruc** [comment]
Is this replaced entirely by #78 ?

**Comment by VourMa** [comment]
> Is this replaced entirely by #78 ?

I think so. @cerminar can you confirm?

**Comment by cerminar** [comment]
Hello @VourMa , actually I would prefer if you could make a PR against my branch so that I can keep working on #78 since I have more changes in the pipeline. 
Ops, ignore the comment please I misread the whole thread.

**Comment by VourMa** [comment]
No problem, Gianluca.

In any case, I think we can close this PR. Any changes will be ported to #78 through PRs to Gianluca's branch.

**Pull request closed without merging**
