### PR TITLE
Update tdr barrel regionizer emulator

### PR DESCRIPTION
**Pull request by jmitrevs**
#### PR description:

This updates the tdr barrel emulator. It generally matches results with the firmware in:

https://gitlab.cern.ch/cms-cactus/phase2/firmware/correlator-common/-/merge_requests/134

The one issue that remains is that the processing delays are not 100% accurately modeled, so data coming from different fibers can appear in different order in the output between the emulator and the simulation. (The TDR emulator was never 100% accurate on this.) This includes an attempt to model this better, but it's not quite there.

#### PR validation:

This is mainly tested manually comparing emulator and simulator using scripts in in correlator-layer1. I will comment on the related PR once I make it.

### CODE REVIEW

**Comment by gpetruc** [comment]
At a quick look it seems ok to me.
Since this will have to be ported also to cms-l1t-offline and the master branch of central cmssw , I would suggest you to squash all into a single commit  - that would make the rebase to cmssw master easier.

**Comment by jmitrevs** [comment]
For squashing into a single commit, you mean that when this is merged, you will use the "Squash and Merge" option, or is there something I need to do before?

**Comment by gpetruc** [comment]
I think it's best if you squash the commits locally and force-push the new commit here.
That way, you can then also open a PR to cms-l1t-offline with the same branch, and a PR to cmssw master with a rebase of that commit on the latest CMSSW 13_2_X IB

**Comment by jmitrevs** [comment]
I may have a solution to the order problem I am still seeing, so I may want to include a few more commits before squashing. It should be within the next few days.

**Comment by jmitrevs** [comment]
I fixed the order issue and squashed this commit.

**Comment by jmitrevs** [comment]
I pushed another commit here as requested in the review in cms-sw/cmssw#41838. If you agree with the response to that request, we should cherry-pick the answer. If not, let me know what is the best way to fix it.

**Comment by gpetruc** [comment]
Yep, I'll cherry-pick it on the other PRs (monday).

Il Sab 3 Giu 2023, 00:24 Jovan Mitrevski ***@***.***> ha
scritto:

**Comment by gpetruc** [comment]
Ok, the PRs to upstream are not yet merged but they are fully signed so I can merge this.
To stay better in sync with cms-l1t-offline in fact I'll merge the branch used to make https://github.com/cms-l1t-offline/cmssw/pull/1134 which has the cherry-pick of the last commit instead of the original one

**Comment by gpetruc** [comment]
effectively merged.

**Pull request closed without merging**
