### PR TITLE
Update deregionizer inputs emulation for proper CTL1 output ordering

### PR DESCRIPTION
**Pull request by thesps**
When comparing firmware simulation of CTL2 deregionizer using pattern files from `L1Trigger/Phase2L1ParticleFlow/test/make_l1ct_patternFiles_cfg.py` with emulation using the `DeregionizerProducer` collection, there are some discrepancies due to the ordering of the Puppi candidates out of CTL1 into CTL2. This PR:
- updates the handling of the CTL2 inputs, using the CTL1 pattern file writer as reference
- adds some flexibility to redefine the ordering with configuration (effectively how CTL1 and CTL2 are cabled together)
- refactors the `DeregionizerInput` and `DeregionizerEmulator` classes slightly to only do tasks their names imply
- reestablishes matching again between firmware (using the proper CMSSW-produced pattern files) and emulation

MR to correlator-common updating the tests will follow

### CODE REVIEW

**Comment by gpetruc** [comment]
https://gitlab.cern.ch/cms-cactus/phase2/firmware/correlator-common/-/merge_requests/105

**Comment by thesps** [comment]
Ready to merge

**Comment by gpetruc** [comment]
The CI finds some code-formatting issues: 
https://gitlab.cern.ch/cms-cactus/phase2/firmware/correlator-common/-/pipelines/4727476

**Comment by thesps** [comment]
Okay, I've rectified those

**Pull request merged**
